spring:
  application:
    name: fitdaero-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fitdaero}
    username: ${DB_USERNAME:fitdaero}
    password: ${DB_PASSWORD:fitdaero}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
